---
abstract: 'change content of a file atomically'
author:
  - 'HIROSE Masaaki <hirose31 _at_ gmail.com>'
build_requires:
  FindBin: 0
  IO::Scalar: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-File-AtomicChange
no_index:
  directory:
    - inc
    - t
requires:
  File::Copy: 0
  File::Sync: 0
  File::Temp: 0
  Filter::Util::Call: 0
  IO::File: 0
  POSIX: 0
  Path::Class: 0
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hirose31/p5-io-file-atomicchange.git
version: 0.02
